// SEO / social-share check on the built docs/ (GitHub Pages + Coolify serve this folder): required <head> tags, JSON-LD, manifest, referenced assets exist.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const docs = path.join(root, 'docs');
const html = fs.readFileSync(path.join(docs, 'index.html'), 'utf8');
assert.equal(html, fs.readFileSync(path.join(root, 'dist-single/Magic-Colour.html'), 'utf8'), 'docs/index.html == single-file build');
const BASE = 'https://magic-colour.games.mikai.ai/';
const head = html.slice(0, html.indexOf('</head>'));
const meta = (attr, name) => { const m = head.match(new RegExp(`<meta[^>]*\\b${attr}="${name}"[^>]*\\bcontent="([^"]*)"`, 'i')); return m && m[1]; };
const link = (rel) => [...head.matchAll(new RegExp(`<link[^>]*\\brel="${rel}"[^>]*>`, 'gi'))].map((m) => m[0]);
const attr = (tag, a) => (tag.match(new RegExp(`\\b${a}="([^"]*)"`)) || [])[1];
assert.match(html, /<html lang="en">/);
const title = head.match(/<title>([^<]+)<\/title>/)?.[1]; assert.ok(title && title.length >= 20 && title.length <= 80, 'title length ' + title);
const desc = meta('name', 'description'); assert.ok(desc && desc.length >= 70 && desc.length <= 200, 'description');
for (const n of ['viewport', 'theme-color', 'color-scheme', 'robots', 'application-name', 'apple-mobile-web-app-capable', 'apple-mobile-web-app-title', 'twitter:title', 'twitter:description', 'twitter:image', 'twitter:image:alt']) assert.ok(meta('name', n), 'meta ' + n);
assert.equal(meta('name', 'twitter:card'), 'summary_large_image');
for (const n of ['og:title', 'og:description', 'og:site_name', 'og:locale', 'og:image:alt']) assert.ok(meta('property', n), n);
assert.equal(meta('property', 'og:type'), 'website');
assert.equal(meta('property', 'og:url'), BASE);
assert.equal(meta('property', 'og:image'), BASE + 'og-image.png');
assert.equal(meta('property', 'og:image:width'), '1200'); assert.equal(meta('property', 'og:image:height'), '630');
assert.equal(attr(link('canonical')[0], 'href'), BASE);
assert.ok(!/noindex/i.test(meta('name', 'robots')));
const ld = JSON.parse(head.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);
assert.ok([].concat(ld['@type']).includes('WebApplication') && [].concat(ld['@type']).includes('Game'));
assert.equal(ld.url, BASE); assert.equal(ld.image, BASE + 'og-image.png');
assert.equal(ld.applicationCategory, 'Game'); assert.ok(ld.genre && ld.description && ld.name);
assert.ok(ld.audience.suggestedMinAge >= 0); assert.equal(ld.offers.price, '0'); assert.equal(ld.isAccessibleForFree, true);
const exists = (rel) => assert.ok(fs.existsSync(path.join(docs, rel)), 'missing docs/' + rel);
for (const tag of [...link('icon'), ...link('apple-touch-icon'), ...link('manifest')]) exists(attr(tag, 'href'));
const man = JSON.parse(fs.readFileSync(path.join(docs, 'manifest.webmanifest'), 'utf8'));
for (const k of ['name', 'short_name', 'description', 'start_url', 'scope', 'display', 'background_color', 'theme_color', 'categories']) assert.ok(man[k], 'manifest.' + k);
assert.ok(man.icons.some((i) => i.purpose === 'maskable') && man.icons.some((i) => i.sizes === '192x192') && man.icons.some((i) => i.sizes === '512x512'));
for (const i of man.icons) exists(i.src);
const og = fs.readFileSync(path.join(docs, 'og-image.png'));
assert.equal(og.subarray(1, 4).toString(), 'PNG'); assert.equal(og.readUInt32BE(16), 1200); assert.equal(og.readUInt32BE(20), 630); assert.ok(og.length < 300 * 1024, 'og-image too big');
assert.equal(fs.readFileSync(path.join(docs, 'apple-touch-icon.png')).readUInt32BE(16), 180);
exists('404.html'); exists('favicon.ico');
assert.ok(fs.readFileSync(path.join(docs, 'robots.txt'), 'utf8').includes('Sitemap: ' + BASE + 'sitemap.xml'));
assert.ok(fs.readFileSync(path.join(docs, 'sitemap.xml'), 'utf8').includes('<loc>' + BASE + '</loc>'));
// the service worker must keep working: still present, versioned, and precaches only files that exist
const sw = fs.readFileSync(path.join(docs, 'sw.js'), 'utf8');
assert.ok(!sw.includes('__VERSION__'), 'sw version stamped');
for (const f of sw.match(/const FILES = \[([^\]]*)\]/)[1].match(/'[^']+'/g).map((s) => s.slice(1, -1))) if (f !== './') exists(f.replace(/^\.\//, ''));
assert.ok(/serviceWorker[\s\S]{0,120}register\([`"']sw\.js[`"']\)/.test(html), 'sw registration kept');
console.log('seo OK:', title);
